### ISSUE TITLE
Deducting the premise of a scheme from a conclusion prevent its instantiation

### ISSUE THREAD

**Issue by pallix** [carneades/carneades-4#28] opened 2017-03-29 08:54 UTC
Hi again,

In the example below, the scheme fails to be instantiated, because one of its premises, `observed(obs)` is deduced from an argument. Is it a bug? 

```
meta:
  title: something

language:
  concluded/1: "We conclude %s"
  to/2: "%s can conclude %s."
  rendered_obsolete/2: "Theory %s has been rendered obsolete, by some other unknown theory, for observation %s "
  observed/1:  "%s has been observed."
  from/2: "Theory %s can be used to conclude something from %s."
  has_occurred/1: "An event %s has occurred."
  causes/2: "Event %s causes event %s."
  interference/1: "An event has occurred which interferes with event %s."
  will_occur/1: "An event %s will occur."
  t/0: "Theory implies something "
  would_be_known/1: "%s would be known if it were true."
  uninvestigated/1: "The truth of %s has not been investigated."
  known/1: "%s is known to be true."

argument_schemes:

  - id: abduction
    variables: [S,T,H]
    conclusions:
      - concluded(H)
    premises:
      - observed(S)
      - from(T,S)
      - to(T,H)
    exceptions:
      - rendered_obsolete(T,S)

arguments:

  a:
    conclusion: observed(obs)
    premises:
      - heard(obs)

statements:
  technical_mistake: technical mistake
  ¬technical_mistake: not a technical mistake
  observed(obs): observed
  heard(obs): heard

assumptions:
  - heard(obs)
  - from(t,obs)
  - to(t,conc)
```

**Comment by tfgordon** [comment] 2017-03-29 19:48
Currently, arguments are not used to derive further arguments.  Only argumentation schemes

are used to derive arguments, from the assumptions.  So to get your example to work, replace

argument a1 with a scheme such as this one:


  - id: observed1
    variables: [X]
    premises:
      - heard(X)
    conclusions:
      - observed(X

I suppose we could generate propositional schemes (without variables) from the arguments,
but the system was designed to work in the other direction, to generate arguments from schemes.
The arguments in a file are intended to "cache" arguments which have been generated previously
from the schemes, in scenarios where not all arguments are put forward at once, for example in
dialogues.

**Comment by tfgordon** [comment] 2017-03-30 08:16
I have a simplier idea:  all the statements in the graph could be added to the list of CHR goals, along with the assumptions, to be used when generating further arguments.  The statements need not be proven; they can be used hypothetically to generate arguments which would be applicable if their premises were proven.  Possible disadvantage:  too many useless arguments might be generated.

**Comment by pallix** [comment] 2017-03-30 12:33
Ok so only schemes should be used to generate arguments. It seems like a simple sufficient model, and flexible given the expressivity of schemes. Indeed it's not much harder to declare a scheme rather than an argument so I'm not sure for now if using the arguments conclusions to generate schemes is very useful or not.

**Comment by tfgordon** [comment] 2017-03-30 13:29
Ok. Then I will close this issue for now.  If the need comes up, we can consider implementing one of the solutions suggested above.

**Closed by tfgordon** 2017-03-30 13:29 UTC
